# -*- coding: utf-8 -*-
"""Copy of Assignment_1.ipynb.json

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yg-E3t7EhsWM2zxTUm_PV2tlZ2jM1oyg

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"
a= s.split()
print(a)

"""## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742
print('the diameter of {} is {} kilometers'.format(planet, diameter))

"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

"""# Numpy"""

import numpy as np
x=np.array([1,2,3,5])
print (x)
x.size

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

for i in range(11):
   print(i)

np.arange(11)

np.arange(5,11)

"""## 5. Create an array of all the even integers from 20 to 35"""

import numpy as np
array =np.arange(20,35,2)
print(array)

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

import numpy as np
x =np.arange(0,9).reshape(3,3)
print(x)

"""## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

import numpy as np
a =np.array([1,2,3])
b =np.array([4,5,6])
c =np.concatenate((a,b),axis = None)
print(c)

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd
record ={
"Name": ["Raghul","Muthu","Vicky"],"Marks": [85,56,45]}
ml =pd.DataFrame(record)
print(ml)

from google.colab import drive
drive.mount('/content/drive')



"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

from datetime import date, timedelta
sdate = date(2023,1,1)
edate = date(2023,2,11)
def dates_bwn_twodates(start_date, end_date):
    for n in range(int ((end_date - start_date).days)):
        yield start_date + timedelta(n)
print(dates_bwn_twodates(sdate,edate))

import pandas
pandas.date_range(sdate,edate-timedelta(days=1),freq='d')

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
value = pd.DataFrame (lists, columns=['number','name','mark'], dtype =float)
print(value)

